In [19]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as mtick
import plotly.express as px

In [2]:
all_data_df = pd.read_csv("Data/combined_zpallagi.csv")

In [7]:
#function to multiply monetary columns by 1000
def by_thousand(df):
    
    columns_to_multiply = ['AGI_Amt', 'Standar_Ded_Amt', 'Itemized_Ded_Amt', 'Total_Taxes_Amt', 'Charitable_Amt']
    
    try:
        # Multiply monetary columns by 1000 (if columns exist in the DataFrame)
        df[columns_to_multiply] = df[columns_to_multiply] * 1000
    except KeyError as e:
        missing_columns = [col for col in columns_to_multiply if col not in df.columns]
        print(f"Skipping non-existent columns: {missing_columns}")

    return df

In [9]:
all_data_adj = by_thousand(all_data_df)

Skipping non-existent columns: ['Standar_Ded_Amt', 'Total_Taxes_Amt']

In [23]:
#get rid of columns
columns_to_keep = ['id', 'year', 'State', 'new_agi_stub', 'Returns', 'Single', 'Joint',
       'Hd_of_Hshld', 'AGI_Amt','Itemized_Ded_Amt',
       'Charitable_Returns', 'Charitable_Amt']
plotable_df = all_data_adj[columns_to_keep]

In [24]:
plotable_df.head()

,id,year,State,new_agi_stub,Returns,Single,Joint,Hd_of_Hshld,AGI_Amt,Itemized_Ded_Amt,Charitable_Returns,Charitable_Amt
0,0,2012,AL,1.0,889920.0,490850.0,129070.0,256900.0,11517112.0,850798.0,46490.0,121095.0
1,1,2012,AL,2.0,491150.0,194370.0,159200.0,123350.0,17617800.0,1914481.0,103450.0,358997.0
2,2,2012,AL,3.0,254280.0,68160.0,148960.0,31480.0,15644666.0,1914831.0,96530.0,404644.0
3,3,2012,AL,4.0,160160.0,23020.0,126140.0,9030.0,13885434.0,1770415.0,81870.0,406140.0
4,4,2012,AL,5.0,183320.0,15880.0,161260.0,4890.0,24641055.0,3383365.0,131170.0,849342.0

In [44]:
grouped = plotable_df.groupby('new_agi_stub')
#mean_bins = grouped['Charitable_Amt'].mean()

In [46]:
grouped.head()

,id,year,State,new_agi_stub,Returns,Single,Joint,Hd_of_Hshld,AGI_Amt,Itemized_Ded_Amt,Charitable_Returns,Charitable_Amt
0,0,2012,AL,1.0,889920.0,490850.0,129070.0,256900.0,11517112.0,850798.0,46490.0,121095.0
1,1,2012,AL,2.0,491150.0,194370.0,159200.0,123350.0,17617800.0,1914481.0,103450.0,358997.0
2,2,2012,AL,3.0,254280.0,68160.0,148960.0,31480.0,15644666.0,1914831.0,96530.0,404644.0
3,3,2012,AL,4.0,160160.0,23020.0,126140.0,9030.0,13885434.0,1770415.0,81870.0,406140.0
4,4,2012,AL,5.0,183320.0,15880.0,161260.0,4890.0,24641055.0,3383365.0,131170.0,849342.0
5,5,2012,AL,6.0,44840.0,3420.0,40370.0,750.0,21926706.0,2570907.0,40870.0,824648.0
6,6,2012,AK,1.0,128930.0,98750.0,13120.0,13880.0,1482918.0,70709.0,2460.0,4791.0
7,7,2012,AK,2.0,80860.0,44370.0,20740.0,12860.0,2951291.0,169387.0,6650.0,17280.0
8,8,2012,AK,3.0,51160.0,21860.0,22000.0,5840.0,3155691.0,256775.0,10370.0,31973.0
9,9,2012,AK,4.0,35010.0,9740.0,22250.0,2460.0,3038502.0,281076.0,10610.0,39831.0
10,10,2012,AK,5.0,50730.0,7090.0,41550.0,1730.0,6834249.0,641421.0,23770.0,108270.0
11,11,2012,AK,6.0,12300.0,1340.0,10640.0,300.0,5403108.0,375682.0,8760.0,104337.0
12,12,2012,AZ,1.0,1085900.0,654630.0,171350.0,248620.0,14266039.0,1369006.0,62260.0,100011.0
13,13,2012,AZ,2.0,688770.0,308100.0,214090.0,155070.0,24731298.0,2553431.0,125060.0,257697.0
14,14,2012,AZ,3.0,359060.0,122890.0,189880.0,41390.0,22077484.0,2944773.0,135790.0,348579.0
15,15,2012,AZ,4.0,224650.0,47510.0,160640.0,14690.0,19443169.0,2805523.0,119420.0,372934.0
16,16,2012,AZ,5.0,272270.0,35180.0,225530.0,10060.0,36410108.0,5495612.0,197690.0,823608.0
17,17,2012,AZ,6.0,78950.0,8920.0,67220.0,2380.0,39263597.0,4959051.0,71110.0,1023602.0
18,18,2012,AR,1.0,531290.0,302120.0,91660.0,127800.0,6797465.0,377052.0,17350.0,47850.0
19,19,2012,AR,2.0,302370.0,115240.0,115330.0,63030.0,10829473.0,831768.0,40020.0,142298.0
20,20,2012,AR,3.0,156110.0,37760.0,102030.0,13530.0,9623125.0,967590.0,44210.0,183016.0
21,21,2012,AR,4.0,91980.0,11910.0,75830.0,3530.0,8011297.0,973945.0,41380.0,196717.0
22,22,2012,AR,5.0,95090.0,8640.0,83820.0,2170.0,12851960.0,1884986.0,67040.0,398754.0
23,23,2012,AR,6.0,24730.0,2250.0,21940.0,460.0,14545624.0,1781325.0,22350.0,424572.0
24,24,2012,CA,1.0,6404780.0,4198010.0,938340.0,1194820.0,81950048.0,8162340.0,290010.0,444698.0
25,25,2012,CA,2.0,3851420.0,1776130.0,1178070.0,834220.0,138870904.0,16391849.0,687520.0,1377136.0
26,26,2012,CA,3.0,2145000.0,858840.0,950580.0,299540.0,131910234.0,21422688.0,854480.0,2010608.0
27,27,2012,CA,4.0,1361280.0,415210.0,806110.0,121990.0,117875012.0,21884690.0,790590.0,2131998.0
28,28,2012,CA,5.0,2005070.0,384930.0,1501310.0,101260.0,274055549.0,54600734.0,1536490.0,5388583.0
29,29,2012,CA,6.0,799120.0,105430.0,663160.0,22910.0,460171958.0,78901180.0,717370.0,11367131.0